import { NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/auth';
import { db } from '@/lib/db';
import { z } from 'zod';
const optionSchema=z.object({text:z.string().min(1),correct:z.boolean()});
const questionSchema=z.object({prompt:z.string().min(2),explanation:z.string().optional().default(''),options:z.array(optionSchema).min(2)}).refine(v=>v.options.filter(o=>o.correct).length===1,'Each question must have exactly one correct option.');
const schema=z.object({lessonId:z.string().min(1),title:z.string().min(2),instructions:z.string().optional().default(''),passScore:z.number().int().min(1).max(100),attemptLimit:z.number().int().min(1).nullable(),published:z.boolean(),questions:z.array(questionSchema).min(1)});
export async function POST(request:Request){await requireAdmin();const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||'Invalid quiz.'},{status:400});const d=parsed.data;const quiz=await db.$transaction(async tx=>{const saved=await tx.quiz.upsert({where:{lessonId:d.lessonId},update:{title:d.title,instructions:d.instructions,passScore:d.passScore,attemptLimit:d.attemptLimit,published:d.published},create:{lessonId:d.lessonId,title:d.title,instructions:d.instructions,passScore:d.passScore,attemptLimit:d.attemptLimit,published:d.published}});await tx.quizQuestion.deleteMany({where:{quizId:saved.id}});for(let qi=0;qi<d.questions.length;qi++){const q=d.questions[qi];const made=await tx.quizQuestion.create({data:{quizId:saved.id,prompt:q.prompt,explanation:q.explanation,position:qi+1}});await tx.quizOption.createMany({data:q.options.map((o,oi)=>({questionId:made.id,text:o.text,correct:o.correct,position:oi+1}))})}return tx.quiz.findUniqueOrThrow({where:{id:saved.id},include:{questions:{orderBy:{position:'asc'},include:{options:{orderBy:{position:'asc'}}}}}})});return NextResponse.json({quiz})}
export async function DELETE(request:Request){await requireAdmin();const lessonId=new URL(request.url).searchParams.get('lessonId');if(!lessonId)return NextResponse.json({error:'Lesson is required.'},{status:400});await db.quiz.deleteMany({where:{lessonId}});return NextResponse.json({ok:true})}
