import { revalidatePath } from 'next/cache';
import { requireActiveUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { Shell } from '@/components/shell';
import { PushNotificationSettings } from '@/components/push-notification-settings';

const fonts=['Arial','Verdana','Georgia','Trebuchet MS','Tahoma'];
const languages=[['en','English'],['cy','Welsh'],['fr','French'],['de','German'],['es','Spanish'],['it','Italian'],['nl','Dutch'],['pt','Portuguese']];
export default async function SettingsPage(){const user=await requireActiveUser();async function save(fd:FormData){'use server';const me=await requireActiveUser();await db.user.update({where:{id:me.id},data:{pageColour:String(fd.get('pageColour')||'#f7faff'),accentColour:String(fd.get('accentColour')||'#246bfd'),textColour:String(fd.get('textColour')||'#10243e'),fontFamily:String(fd.get('fontFamily')||'Arial'),language:String(fd.get('language')||'en')}});revalidatePath('/settings');revalidatePath('/dashboard');}return <Shell user={user}><div className="page-title"><p className="eyebrow">PERSONALISATION</p><h1>Appearance and language</h1><p>Choose how the Academy looks and feels for your account.</p></div><form action={save} className="card form-grid settings-grid"><label>Page colour<input type="color" name="pageColour" defaultValue={user.pageColour}/></label><label>Accent colour<input type="color" name="accentColour" defaultValue={user.accentColour}/></label><label>Text colour<input type="color" name="textColour" defaultValue={user.textColour}/></label><label>Font<select name="fontFamily" defaultValue={user.fontFamily}>{fonts.map(f=><option key={f}>{f}</option>)}</select></label><label>Language<select name="language" defaultValue={user.language}>{languages.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><div className="full theme-preview" style={{background:user.pageColour,color:user.textColour,fontFamily:user.fontFamily,borderColor:user.accentColour}}><strong>Live preview</strong><p style={{color:user.textColour}}>Your Academy pages will use these colours and this font.</p><span style={{background:user.accentColour}}>Accent</span></div><button className="primary">Save settings</button></form><section className="section-block"><div className="page-title compact"><p className="eyebrow">NOTIFICATIONS</p><h2>Browser push notifications</h2></div><PushNotificationSettings publicKey={process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY || ''}/></section></Shell>}
